kind: pipeline
name: default
trigger:
  branch:
    - main
  event:
    - push
    - tag
steps:
- name: beardedtek-PUSH
  image: plugins/docker
  when:
    event:
      - push
      - tag
  settings:
    username: beardedtek
    password:
      from_secret: docker_password
    repo: docker.beardedtek.com/beardedtek-com/fevr-base
    registry: docker.beardedtek.com
    tags: 0.6,0.7-dev
    experimental: true
    compress: true
    squash: true
image_pull_secrets:
  - docker-auth-beardedtek.com
